apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "health-chain"
---
apiVersion: com.healthchain/v1
kind: Deployment
metadata:
  name: health-chain-node-1
  namespace: "health-chain"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "HealthChain"
    spec:
      containers:
      - name: health-chain
        image: health-chain:0.1.0-SNAPSHOT
        readinessProbe:
          httpGet:
            path: /ready
            port: management
        livenessProbe:
          httpGet:
            path: /alive
            port: management
        ports:
          - name: management
            containerPort: 8558
            protocol: TCP
          - name: http
            containerPort: 8080
            protocol: TCP
        resources:
          limits:
            memory: 1024Mi
          requests:
            cpu: 1
            memory: 512Mi