apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: health-chain
  name: health-chain
  namespace: health-chain
spec:
  replicas: 3
  selector:
    matchLabels:
      app: health-chain
  template:
    metadata:
      labels:
        app: health-chain
        actorSystemName: HealthChain
    spec:
      containers:
      - name: health-chain
        image: health-chain:0.1.0-SNAPSHOT
        imagePullPolicy: Never
        readinessProbe:
          httpGet:
            path: /ready
            port: management
          periodSeconds: 10
          failureThreshold: 10
          initialDelaySeconds: 20
        livenessProbe:
          httpGet:
            path: /alive
            port: management
          periodSeconds: 10
          failureThreshold: 10
          initialDelaySeconds: 20
        ports:
          - name: management
            containerPort: 8558
            protocol: TCP
          - name: http
            containerPort: 8080
            protocol: TCP
        resources:
          limits:
            memory: 1024Mi
          requests:
            cpu: 1
            memory: 512Mi
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
subjects:
  - kind: User
    name: system:serviceaccount:health-chain:default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
    